name: MacOS (Intel/Apple Silicon) Build

on:
  push:
    branches:
      - release
  
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        include:
          - platform: 'macos-latest' # Apple Silicon Macs
            args: '--target aarch64-apple-darwin'
            arch: 'aarch64'
          - platform: 'macos-latest' # Intel Macs
            args: '--target x86_64-apple-darwin'
            arch: 'x86_64'
    
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: 'aarch64-apple-darwin,x86_64-apple-darwin'

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
            workspaces: './src-tauri -> target'
        
      - name: install frontend dependencies
        run: bun install

      - name: Build App
        run: |
          echo "Building for ${{ matrix.arch }} Mac OS"
          bun tauri build ${{matrix.args}} --bundles dmg
          # Rename the ${{matrix.arch}} build and store the filename
          cd src-tauri/target/${{matrix.arch}}-apple-darwin/release/bundle/dmg/
          for f in *.dmg; do
            mv "$f" "intel-$f"
            echo "${{matrix.arch}}_DMG_PATH=src-tauri/target/${{matrix.arch}}-apple-darwin/release/bundle/dmg/$f" >> $GITHUB_ENV
          done

      - name: Get version from package.json
        id: version
        run: echo "version=$(bun -p "require('./package.json').version")"

      - name: Create draft release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: 'App v${{ steps.version.outputs.version }}'
          tag_name: 'v${{ steps.version.outputs.version }}'
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Upload Build to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ${{ matrix.arch == 'aarch64' && env.aarch64_DMG_PATH || env.x86_64_DMG_PATH }}
            asset_name: ${{ matrix.arch}}-App.dmg
            asset_content_type: application/x-apple-diskimage