name: 'publish'

on:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # Apple Silicon Macs
            args: '--target aarch64-apple-darwin'
            arch: 'aarch64'
          - platform: 'macos-latest' # Intel Macs
            args: '--target x86_64-apple-darwin'
            arch: 'x86_64'
    
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: 'aarch64-apple-darwin,x86_64-apple-darwin'

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
            workspaces: './src-tauri -> target'
        
      - name: install frontend dependencies
        run: bun install

      - name: Build App
        run: |
          echo "Building for ${{ matrix.arch }} Mac OS"
          bun tauri build ${{matrix.args}} --bundles dmg
          # Rename the ${{matrix.arch}} build and store the filename
          cd src-tauri/target/${{matrix.arch}}-apple-darwin/release/bundle/dmg/
          for f in *.dmg; do
            mv "$f" "intel-$f"
            echo "${{matrix.arch}}_DMG_PATH=src-tauri/target/${{matrix.arch}}-apple-darwin/release/bundle/dmg/$f" >> $GITHUB_ENV
          done

      - name: Get version from package.json
        id: version
        run: echo "version=$(bun -p "require('./package.json').version")"

      - name: Upload Build to Release
        if: github.event.inputs.release_upload_url != ''
        uses: actions/upload-release-asset@v1
        with:
            upload_url: ${{ github.event.inputs.release_upload_url }}
            asset_path: ${{ env.matrix.arch_DMG_PATH }}
            asset_name: ${{ matrix.arch}}-App.dmg
            asset_content_type: application/x-apple-diskimage